apiVersion: v1
kind: Service
metadata:
  name: audit-nodeport-svc
  labels:
    app: audit-nodeport-svc
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30000
    targetPort: 80
  selector:
    app: audit